apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  chart:
    spec:
      chart: qbittorrent
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: apps
      version: 0.3.5
  interval: 1h
  values:
    persistence:
      downloads:
        enabled: true
        mountPath: /downloads
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi
      media:
        enabled: true
        mountPath: /media
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi
