
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: apps
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: apps
      version: 5.0.0
  interval: 1h
  values:
    nextcloud.host: nextcloud.homelab.haseebmajid.dev
    nextcloud.configs:
      config.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
            2 => '100.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          'overwriteprotocol' => 'https',
          'overwrite.cli.url' => 'https://nextcloud.homelab.haseebmajid.dev',
        );

    serviceMonitor:
      enabled: true

    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 8Gi

    metrics:
      enabled: true

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: nextcloud
            password: changeme
            database: nextcloud

      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"

      rbac:
        enabled: true
        serviceaccount:
          create: true
          name: nextcloud-serviceaccount

