apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: apps
spec:
  chart:
    spec:
      chart: tandoor
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: apps
      version: 0.9.5
  interval: 1h
  values:
    env:
      REMOTE_USER_AUTH: "1"
      SOCIAL_DEFAULT_ACCESS: "1"
      SOCIAL_DEFAULT_GROUP: "guest"
      SOCIALACCOUNT_PROVIDERS:
        valueFrom:
          secretKeyRef:
            name: tandoor
            key: providers
      SOCIAL_PROVIDERS: "allauth.socialaccount.providers.openid_connect"
    persistence:
      config:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        mountPath: /opt/recipes/mediafiles
        retain: true
        accessMode: ReadWriteOnce
        size: 1Gi
      static:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/staticfiles
      django-js-reverse:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/cookbook/static/django_js_reverse
    postgresql:
      enabled: true
      auth:
        database: tandoor
        postgresPassword: changeme
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 8Gi
