apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: apps
spec:
  chart:
    spec:
      chart: tandoor
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: apps
      version: 0.9.5
  interval: 1h
  values:
    common:
      ingress:
        main:
          enabled: true
          hosts:
            - host: recipes.homelab.haseebmajid.dev
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    name: tandoor
                    port: 80
      tls:
        - hosts:
            - recipes.homelab.haseebmajid.dev
          secretName: recipes-haseebmajid-dev-tls
    persistence:
      config:
        enabled: true
        retain: true
        storageClass: ""
        accessMode: ReadWriteOnce
        size: 10Gi
