apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: auth
      version: 2024.4.2
  interval: 1h
  values:
    authentik:
      secret_key:
        valuesFrom:
        - secretKeyRef:
            name: authentik
            key: secret_key
      postgresql:
          password: "ThisIsNotASecurePassword"
    server:
      ingress:
        ingressClassName: traefik
        enabled: true
        annotations:
          kubernetes.o/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: auth.homelab.haseebmajid.dev
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
          - auth.homelab.haseebmajid.dev
        secretName: auth-haseebmajid-dev-tls
    postgresql:
        enabled: true
        auth:
            password: "ThisIsNotASecurePassword"
    redis:
        enabled: true
