
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: apps
spec:
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: oben01
        namespace: apps
      version: 1.2.5
  interval: 1h
  values:
    persistence:
      - name: homarr-config
        enabled: true
        storageClassName: "local-path"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/data/configs"
      - name: homarr-database
        enabled: true
        storageClassName: "local-path"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/database"
      - name: homarr-icons
        enabled: true
        storageClassName: "local-path"
        accessMode: "ReadWriteOnce"
        size: "50Mi"
        mountPath: "/app/public/icons"
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: homarr.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - homarr.homelab.haseebmajid.dev
          secretName: homarr-haseebmajid-dev-tls


