
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: apps
spec:
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: apps
      version: 3.0.1
  interval: 1h
  values:
    jellyfin:
      mediaVolumes:
        - name: movies
          existingClaim: jellyfin-pvc
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hostname: jellyfin.homelab.haseebmajid.dev
      path: /
      pathType: ImplementationSpecific
      tls: true
