
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  chart:
    spec:
      chart: test-uptime
      sourceRef:
        kind: HelmRepository
        name: k3
        namespace: monitoring
      version: 1.3.6
  interval: 1h
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - uptime.homelab.haseebmajid.dev
      tls:
        enabled: true
        secretName: uptime-haseebmajid-dev-tls


