apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: apps
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: apps
      version: 0.2.60
  interval: 1h
  values:
    configuration:
      enabled: true
      forceInit: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: home.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - home.homelab.haseebmajid.dev
          secretName: home-haseebmajid-dev-tls
    podSecurityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
          - NET_BROADCAST
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: "longhorn"


