apiVersion: v1
kind: Secret
metadata:
  name: twingate-evasive-tuna
  namespace: auth
type: Opaque
stringData:
  TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:7bwLegQuwYeyPl9vkHx3mFDvrLbPgMB74yYw9gkAa4heaGfhVQDcC08kPG51+Wu0eepbsu9PZF8vGZQ9DcZNycCJvTczB3+nJj8G6dV7SlRWWxCAEpnE4qTwtooL2u/meqhdpQW2WhWOMhi3cuY1xYksjVwLsP545jSI1bBEVsQGZQeciBKvrdhv9fr5y/KOBxnuysBwy8eL/Bq3y0zeHJ164xneNy4eniEn0o9zsY1RYl0qFDdcRLjXhMg+731OuJ0VX+/onRvGkGm1zwRY18mcqLibLapGpH+JL8xYGEfaJOupHry4QP2YypWlKC5VBsparyNYzlfEdU68yq58YyVuHZv728nOuCGe6vKo2mdXnFA8vV5Rw17T6vrTAoxm8V0bo2jj33/1i8qzx+Yz7MKbcyOf0Ngyha/P321j/2a6mIABIrzk3kPchAUnlUhGgmkCCGeXpuXMEJwrdUU4EBSNAsuDJpREvTK/PMwNaEQKzXSyNQ7yMD347vIqK195HikYpUA6F4iOy2dHVqaZ8KnhKsXU7D9vUnwtvjNIJv5Gh2b2rfTDbcLRWeUsB/mutuR46S/obDhKEYqjMPMDlVm6OTUlTnhqd+2WA6kb+jYGR2TPWynDNiEqbJaL7A==,iv:MgSLG2EWy45kTXyT9XnOsnp6i6nHoa9NMp9ipdVwMy4=,tag:ni3xkj/Mq6AQ9zyCOCN1NA==,type:str]
  TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:2o/pK/Bap5NF6U7OT/QV7wCpe7NNTPt7HexJZWNNn1o9qvDJQnU1xRDyHaJmMSy7HAzuGv/GTksw+ybH64fzL+U83gX66OkCxPY+hixjPUE4V8+pHKlz4YkUt6QNk7emPPU4xc95PIRL7MhIUMyGIIePv9h3S+IJC870C1ifL+BkvNJzf4I=,iv:ml3NzK69z8pfMMsm+dmdKAxv1Z9bpvTd2fCCOfn/LVo=,tag:mP1NQQ/RCADVcQhjtje/fQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aW9HRGtTVDc1QzAwSE5v
        djFwVEtsVTREYnVueTBqRTRPaHdJV09penk4ClZLMm1VRGlPL0kweFNacHZaYXBk
        TnloMkhPQm1PRkdQK2VzRERDYmJZaVkKLS0tIDcvc0JsZlM1eURLa1hVQjRhK3J2
        SmFtU21QbndyS2dPSDBuVHRaTG5RZEEKzAEFQivrdIbLbQZOooG159z3E55E8eKV
        MjPCy86d9ljCqrXb+kdDRPgFjYmzAtH6yr1kmKRCJ1bRrKOg9ZuQXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-23T18:24:12Z"
  mac: ENC[AES256_GCM,data:2vfjaWK99lTgAdCkAiw1a7xMFmFfCNcICDijI4kFPtO8i/tOOuTzEMHhoVCuOWoP77CBKuzZuy66GORAmRl23NZj3YzIOZ427xGuDB+bWfhyoYWXPUfHBjrJAXRmUsCBRzlxR6Av3vsMsE/NM49UqP/0LqQ9mFwlg2hX9A/wqVw=,iv:q18ds1fiJs0YKsZKf7r8ukpA+oBnVf8RnYm0AX+MrXc=,tag:t7LFqY9KZp0yhnGQxaCnkQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
