apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate-venomous-centipede
  namespace: auth
spec:
  chart:
    spec:
      chart: connector
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: auth
      version: 0.1.25
  interval: 1h
  values:
    connector:
      network: "majiy00"
      existingSecret: "twingate-venomous-centipede"
