apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: apps
spec:
  chart:
    spec:
      chart: prowlarr
      sourceRef:
        kind: HelmRepository
        name: adminafk
        namespace: apps
      version: 0.3.2
  interval: 1h
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: prowlarr.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - prowlarr.homelab.haseebmajid.dev
          secretName: prowlarr-haseebmajid-dev-tls
