apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wger
  namespace: apps
spec:
  chart:
    spec:
      chart: wger
      sourceRef:
        kind: HelmRepository
        name: wger
        namespace: apps
      version: 0.2.0
  interval: 1h
  values:
    app:
      persistence:
        enabled: true
        storageClass: "longhorn"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      url: wger.homelab.haseebmajid.dev
      tls: true
      annotations:
        spec.ingressClassName: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
