apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    volumes:
      - name: wildcard-haseebmajid-dev-tls
        mountPath: /certs
        type: secret
      - name: traefik-dynamic-config
        mountPath: /config
        type: configMap

    additionalArguments:
      - --providers.file.filename=/config/dynamic.yaml
