apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
        namespace: gitlab
      version: 0.65.0
  interval: 1m0s
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
    runners:
      secret: gitlab-runner-secret


