apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: apps
spec:
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: adminafk
        namespace: apps
      version: 0.4.0
  interval: 1h
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.middlewares: "auth-ak-outpost-authentik-embedded-outpost@kubernetescrd"
      hosts:
        - host: sonarr.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - sonarr.homelab.haseebmajid.dev
          secretName: sonarr-haseebmajid-dev-tls
