apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: hello@haseebmajid.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - dns01:
      cloudflare:
        email: hello@haseebmajid.dev
        apiKeySecretRef:
          name: cert-manager-secrets
          key: cloudflare-api-key
