
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: 60.0.2
  interval: 1m0s
  values:
    alertmanager:
      ingress:
        enabled: true
        className: traefik
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - alertmanager.homelab.haseebmajid.dev
        tls:
          - hosts:
              - alertmanager.homelab.haseebmajid.dev
            secretName: alertmanager-haseebmajid-dev-tls
    grafana:
      grafana.ini:
          auth:
              signout_redirect_url: "https://auth.homelab.haseebmajid.dev/application/o/grafna/end-session/"
              oauth_auto_login: true
          auth.generic_oauth:
              name: authentik
              enabled: true
              client_id:
                valueFrom:
                  secretKeyRef:
                    name: grafana-oauth
                    key: client-id
              client_secret:
                valueFrom:
                  secretKeyRef:
                    name: grafana-oauth
                    key: client-secret
              scopes: "openid profile email"
              auth_url: "https://auth.homelab.haseebmajid.dev/application/o/authorize/"
              token_url: "https://auth.homelab.haseebmajid.dev/application/o/token/"
              api_url: "https://auth.homelab.haseebmajid.dev/application/o/userinfo/"
      ingress:
        enabled: true
        className: traefik
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        paths: /
        hosts:
          - grafana.homelab.haseebmajid.dev
        tls:
          - hosts:
              - grafana.homelab.haseebmajid.dev
            secretName: grafana-haseebmajid-dev-tls
    prometheus:
      ingress:
        enabled: true
        className: traefik
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - prometheus.homelab.haseebmajid.dev
        tls:
          - hosts:
              - prometheus.homelab.haseebmajid.dev
            secretName: prometheus-haseebmajid-dev-tls



