---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: database
spec:
  interval: 1m0s
  provider: generic
  url: https://cloudnative-pg.github.io/charts
